dist: trusty
sudo: required
language: java

# UI-tests will only run on macOS, so we skip these here
script: 
  - mvn -T 1C clean org.jacoco:jacoco-maven-plugin:prepare-agent verify -Pskip-ui-tests
  - sonar-scanner
jdk:
  - oraclejdk11
addons:
  sonarcloud:
    organization: "turesheim-github"
    token:
      secure: "fmYWxhxPFrNTDrA0Wpqg0iBB6o+JIbl9g9Jba/VQYnqZ6YmSBlt1gUS88YmhWCQEQ3UmvvmagoQ+vZysbVzKz/urfJc4V/6Wbvk4kLcdvCuO1lRs/M7m1RGEJGzYXPVDn0Fs65lm9uVQboc3PgyebOP6C9UJTChVkx6qe7rtyY4="
cache:
  directories:
  - "$HOME/.m2"
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true   
  file: "${HOME}/build/${TRAVIS_REPO_SLUG}/net.resheim.eclipse.launcher-site/target/net.resheim.eclipse.launcher-*.zip"
  api_key:
    secure: iVJL4mNY5GG6o32foel+hVV6wDgfg6uMi2G5iHd3lzDdhgtrkqeWcfdJu/gVl7MmQiJzevnnBFbOLpsvXj0RDMEuYWszrnf9ke87P8vqMvpMkoDRHh9z0gaEq4pnsb4BQMxdU+RYOvbXZc7VKuChwxyT5TX35XWZbIJtVyBwaa0=
  on:
    repo: turesheim/eclipse-launcher
    tags: true
    all_branches: true
